name: apk comile

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: run
      run: |
        git clone https://github.com/rojer95/netease-cloud-music-tv-rn.git
        cd netease-cloud-music-tv-rn && yarn install
        yarn release
        ls -l
        # cd android && ./gradlew assembleRelease
